import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SideBarProvider } from "@/components/providers/side-bar-provider";
import { Suspense } from "react";
import { LoadingFallback } from "@/components/LoadingFallback";
import { TanstackQueryProvider } from "@/components/providers/tenstack-query-provider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Learn lang chain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<LoadingFallback />}>
          <TanstackQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SideBarProvider>
                <Toaster/>
                {children}
              </SideBarProvider>
            </ThemeProvider>
          </TanstackQueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
